services:
  contentgeo-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contentgeo-mcp
    ports:
      - "8000:8000"
    environment:
      - MCP_PORT=8000
      # Uncomment and set your API key if you have one
      # - CONTENT_API_KEY=your_api_key_here
    restart: unless-stopped
    volumes:
      - .:/app
    networks:
      - contentgeo-network

networks:
  contentgeo-network:
    driver: bridge 