FROM python:3.9-slim

WORKDIR /app

# Копіюємо файли проекту
COPY . .

# Встановлюємо залежності
RUN pip install --no-cache-dir -r requirements.txt

# Запускаємо сервер
CMD ["python", "contentgeo_server.py"]